-- Pulse cloud account + library schema
-- Run this once in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.liked_songs (
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id text not null,
  video_id text,
  title text not null,
  artist text,
  album text,
  thumb text,
  added_at timestamptz not null default now(),
  primary key (user_id, song_id)
);

create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.playlist_songs (
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  song_id text not null,
  video_id text,
  title text not null,
  artist text,
  album text,
  thumb text,
  position integer not null default 0,
  added_at timestamptz not null default now(),
  primary key (playlist_id, song_id)
);

create table if not exists public.user_interests (
  user_id uuid not null references auth.users(id) on delete cascade,
  interest_type text not null,
  interest_value text not null,
  score double precision not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, interest_type, interest_value)
);

create table if not exists public.listening_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id text not null,
  title text,
  artist text,
  album text,
  event_type text not null check (event_type in ('play','like','unlike','search')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.liked_songs enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_songs enable row level security;
alter table public.user_interests enable row level security;
alter table public.listening_events enable row level security;

drop policy if exists "profiles own" on public.profiles;
create policy "profiles own" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "liked own" on public.liked_songs;
create policy "liked own" on public.liked_songs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "playlists own" on public.playlists;
create policy "playlists own" on public.playlists for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "playlist songs own" on public.playlist_songs;
create policy "playlist songs own" on public.playlist_songs for all using (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid())) with check (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid()));
drop policy if exists "interests own" on public.user_interests;
create policy "interests own" on public.user_interests for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "events own" on public.listening_events;
create policy "events own" on public.listening_events for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, username, display_name)
  values (new.id, split_part(new.email, '@', 1), coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
